# We use our own Perl setup (language "generic" uses a stripped-down TravisCI image)
language: generic

# Ubuntu 14.04 "Trusty"
dist: trusty
# Run in Docker container instead of VM - currently (2016-12-14) beta for "trusty"
sudo: required

env:
    global:
        - OXI_TEST_DB_MYSQL_NAME=openxpki
        - OXI_TEST_DB_MYSQL_USER=openxpki
        - OXI_TEST_DB_MYSQL_PASSWORD=openxpki
        - OXI_TEST_DB_MYSQL_DBHOST=localhost
        - OXI_TEST_DB_MYSQL_DBPORT=3306
        - OXI_TEST_DB_MYSQL_DBUSER=root
        - OXI_TEST_DB_MYSQL_DBPASSWORD=

cache:
    directories:
        - $HOME/perl5/lib/perl5

#
# OS packages
#
addons:
  apt:
    packages:
    - libmysqlclient-dev
    - openssl
    - libssl-dev
    - pkg-config
  mariadb: '10.1'

#
# Service setup
#

before_install:
    - ./tools/scripts/mysql-wait-for-db.sh
    - ./tools/scripts/mysql-create-db.sh
    - ./tools/scripts/mysql-create-user.sh
    - curl -s -L https://cpanmin.us | perl - App::cpanminus
    - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)

#
# Dependencies / modules
#
install:
    - cpanm --quiet --notest PPI
    - ./tools/scripts/makefile2cpanfile.pl > ./cpanfile
    - cpanm --quiet --notest --installdeps ./

#
# Build
#
# (must be specified if "language" is "generic")
script:
    - which perl
    - perl -v
# Compilation
    - pushd core/server
    - sed -ri 's/^(WriteMakefile.*)/\1\nMAN1PODS=>{},\nMAN3PODS=>{},/' Makefile.PL
    - perl Makefile.PL
    - make
# Unit tests
    - make test
# Installation
    - make install
    - popd
# Configuration
    - 'export TRAVIS_USER=$(whoami)'
    - 'export TRAVIS_USERGROUP=$(getent group $TRAVIS_USER | cut -d: -f1)'
    - sudo echo "$TRAVIS_USER / $TRAVIS_USERGROUP"
    - sudo mkdir -p              /var/openxpki/session
    - sudo chown -R $TRAVIS_USER /var/openxpki
    - sudo mkdir -p              /var/log/openxpki
    - sudo chown -R $TRAVIS_USER /var/log/openxpki
    - sudo cp -R ./config/openxpki /etc
    - sudo sed -ri 's/^(user:\s+)\S+/\1'$TRAVIS_USER'/'       /etc/openxpki/config.d/system/server.yaml
    - sudo sed -ri 's/^(group:\s+)\S+/\1'$TRAVIS_USERGROUP'/' /etc/openxpki/config.d/system/server.yaml
    - sudo sed -ri 's/^(pid_file:\s+)\S+/\1\/var\/openxpki\/openxpkid.pid/' /etc/openxpki/config.d/system/server.yaml
    - sudo cat /etc/openxpki/config.d/system/server.yaml
    - sudo ./tools/scripts/mysql-oxi-config.sh
    - sudo chown -R $(whoami) /etc/openxpki
# Database re-init and sample config (CA certificates etc.)
    - ./tools/scripts/mysql-create-db.sh
    - ./tools/scripts/mysql-create-schema.sh
    - ./tools/testdata/insert-test-certificates.sh
# Start OpenXPKI (is in PATH)
    - openxpkictl start || cat /var/log/openxpki/*
# QA tests
    - pushd ./qatest/backend/nice/  && prove -q .
    - popd
    - pushd ./qatest/backend/api/   && prove -q .
    - popd
    - pushd ./qatest/backend/webui/ && prove -q .
    - popd
