language: perl

# Note: language-pack-de is needed for the i18n test
before_install:
#    - sudo apt-get update -qq
    - sudo apt-get install -qq expat libexpat-dev openssl libssl libssl-dev language-pack-de

# Try to get debug from inst stuff
install:
#    - cpanm --notest --verbose --no-interactive Class::Std
#    - cpanm --notest --verbose --no-interactive Class::Std
#    - "(cd trunk/perl-modules/core/trunk && cpanm --installdeps --notest --verbose --no-interactive .)"
#    - "(cd trunk/clients/perl/OpenXPKI-Client && cpanm --installdeps --notest --verbose --no-interactive .)"
    - cpanm --notest Config::Std Config::Merge Template Proc::SafeExec Module::Install YAML
    - "(wget -O Config-Versioned.tar.gz https://github.com/mrscotty/Config-Versioned/tarball/master && tar xzf Config-Versioned.tar.gz)"
# Install Config::Versioned prereqs with --notest before installing Config::Versioned itself
    - "(cd mrscotty-Config-Versioned-* && cpanm --quiet --installdeps --notest .)"
    - "(cd mrscotty-Config-Versioned-* && cpanm --quiet .)"
    - "(wget -O Connector.tar.gz https://github.com/mrscotty/connector/tarball/master && tar xzf Connector.tar.gz)"
    - "(cd mrscotty-connector-* && cpanm --quiet .)"
    - "(cd trunk/perl-modules/core/trunk && cpanm --quiet --installdeps --notest .)"
    - "(cd trunk/clients/perl/OpenXPKI-Client && cpanm --quiet --installdeps --notest .)"
# The core tests depend on the client library - we install it in a separate perlbrew library space
    - "perlbrew lib delete oxi-client; perlbrew lib create oxi-client"
    - "(cd trunk/clients/perl/OpenXPKI-Client && cpanm --quiet --notest .)"

