# .travis.yml
#
# Note: Travis will run through the 'before_install' and 'install' steps
# before executing 'make test'

# We use our own perl, so setting language to generic
# allows us to use the stripped-down travis image
language: generic

# Ubuntu 14.04 "Trusty"
dist: trusty
# Run in Docker container instead of VM - currently (2016-12-14) beta for "trusty"
sudo: false

env:
    global:
        - OXI_TEST_DB_MYSQL_NAME=openxpki
        - OXI_TEST_DB_MYSQL_USER=openxpki
        - OXI_TEST_DB_MYSQL_PASSWORD=openxpki
        - OXI_TEST_DB_MYSQL_DBHOST=127.0.0.1
        - OXI_TEST_DB_MYSQL_DBPORT=3306
        - OXI_TEST_DB_MYSQL_DBUSER=root
        - OXI_TEST_DB_MYSQL_DBPASSWORD=
        # Config::Versioned reads USER env variable
        - USER=dummy

cache:
    directories:
        - $HOME/perl5

addons:
  apt:
    packages:
    - openssl
    - libssl-dev
    - libmysqlclient-dev
    - pkg-config

services:
    - mysql

# Note: language-pack-de is needed for the i18n test
before_install:
    - which perl
    - perl -v
    - ./tools/scripts/mysql-create-db.sh
    - ./tools/scripts/mysql-create-user.sh
    - curl -s -L https://cpanmin.us | perl - App::cpanminus
    - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)

install:
    - cpanm --quiet --notest --installdeps ./

# With 'language: generic', the 'script' must be specified...
script:
    - cd core/server
    - perl Makefile.PL
    - make test
