# .travis.yml
#
# Note: Travis will run through the 'before_install' and 'install' steps
# before executing 'make test'

language: perl

env:
    global:
        - PERL_CPANM_OPT="--mirror http://cpan.cpantesters.org/ --mirror http://search.cpan.org/CPAN --mirror http://cpan.mirrors.travis-ci.org --cascade-search"
        - PATH="/opt/myperl/bin:$PATH"

# Note: language-pack-de is needed for the i18n test
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq expat libexpat-dev openssl libssl-dev language-pack-de

# Try to get debug from inst stuff
install:
    - cpanm --notest Config::Std Config::Merge Template Proc::SafeExec Module::Install YAML DBD::mysql
# Note: Setting PERL=perl causes Makefile.PL to use the perlbrew perl ifrom PATH
    - "(cd core/server && PERL=perl cpanm --quiet --installdeps --notest .)"
# The core tests depend on the client library - we install it in a separate perlbrew library space
#    - "perlbrew lib delete oxi-client; perlbrew lib create oxi-client"
#    - "(cd core/server && cpanm --quiet --notest .)"

