# We use our own Perl setup (language "generic" uses a stripped-down TravisCI image)
language: generic

# Ubuntu 14.04 "Trusty"
dist: trusty
# Run in Docker container instead of VM - currently (2016-12-14) beta for "trusty"
sudo: required

env:
    global:
        - OXI_TEST_DB_MYSQL_NAME=openxpki
        - OXI_TEST_DB_MYSQL_USER=openxpki
        - OXI_TEST_DB_MYSQL_PASSWORD=openxpki
        - OXI_TEST_DB_MYSQL_DBHOST=localhost
        - OXI_TEST_DB_MYSQL_DBPORT=3306
        - OXI_TEST_DB_MYSQL_DBUSER=root
        - OXI_TEST_DB_MYSQL_DBPASSWORD=
        # Config::Versioned reads USER env variable
        - USER=dummy

cache:
    directories:
        - $HOME/perl5/lib/perl5

#
# OS packages
#
addons:
  apt:
    packages:
    - libmysqlclient-dev
    - openssl
    - libssl-dev
    - pkg-config
  mariadb: '10.1'

#
# Service setup
#

before_install:
    - ./tools/scripts/mysql-wait-for-db.sh
    - ./tools/scripts/mysql-create-db.sh
    - ./tools/scripts/mysql-create-user.sh
    - curl -s -L https://cpanmin.us | perl - App::cpanminus
    - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)

#
# Dependencies / modules
#
install:
    - cpanm --quiet --notest PPI
    - ./tools/scripts/makefile2cpanfile.pl > ./cpanfile
    - cpanm --quiet --notest --installdeps ./

#
# Build
#
# (must be specified if "language" is "generic")
script:
    - which perl
    - perl -v
    - cd core/server
    - perl Makefile.PL
    - make test
