# Custom settings for the watchdog
disabled: 0
max_fork_redo: 5
max_exception_threshhold: 10
max_tries_hanging_workflows:  3
# Raise values for prod systems recommended (10/5/1)
interval_wait_initial: 1
interval_loop_idle: 2
interval_loop_run: 1

