main:
    debug: 0
    type: MySQL
    name: openxpki
    host: localhost
    port: 3306
    user: openxpki
    passwd: openxpki

    # extra options passed to the driver as parameter
    #driver:
    #    LongReadLen: 10000000
# To log to a different database copy and adjust the upper block
# logging: ~

