landmark:
  welcome: information!status

main:
  - key: home
    label: Home
    entries: 
      - key:    home!index
        label: Home
      - key:    home!task
        label:  My Tasks
      - key:    home!workflow
        label:  My Workflows
      - key:    home!certificate
        label:  My Certificates

  - key: request
    label: Request
    entries: 
      - key:   workflow!index!wf_type!certificate_signing_request_v2
        label: Request new certificate
      - key:   workflow!index!wf_type!certificate_revocation_request_v2
        label: Request revocation

  - key:   pkiadm
    label: PKI Operation
    entries:
      - key:   workflow!index!wf_type!change_metadata
        label: Change metadata
      - key:   workflow!index!wf_type!crl_issuance
        label: Issue CRL
      - key:   secret!index
        label: Manage Secrets
      - key:   workflow!start!wf_type!ca_publish
        label: Publish CA/CRL


  - key:   info
    label: Information
    entries: 
      - key:   information!issuer
        label: CA certificates
      - key:   crl!index
        label: Revocation lists
      - key:   information!process
        label: Process Information
      - key:   information!status
        label: System Status


  - key:   certificate!search
    label: Certificates

  - key:   workflow!search
    label: Workflows


