head:
    prefix: screvoke
    label: I18N_OPENXPKI_UI_WORKFLOW_TYPE_SMARTCARD_REVOKE_LABEL
    description: I18N_OPENXPKI_UI_WORKFLOW_TYPE_SMARTCARD_REVOKE_DESC

state:
    FAILURE: 
        label: I18N_OPENXPKI_UI_WORKFLOW_STATE_FAILURE_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_STATE_FAILURE_DESC

    SUCCESS: 
        label: I18N_OPENXPKI_UI_WORKFLOW_STATE_SUCCESS_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_STATE_SUCCESS_DESC

    INITIAL: 
        action: 
          - initialize > INITIALIZED

    INITIALIZED:
        autorun: 1
        action:
          - check_authorized_signer > REQUESTOR_AUTHORIZATION_CHECKED

    REQUESTOR_AUTHORIZATION_CHECKED:
        autorun: 1
        action:
          - global_noop > FAILURE ? !is_requestor_authorized
          - check_prereqs_via_api > PREREQS_AVAILABLE ? is_requestor_authorized

    HAVE_CERT_TO_REVOKE:
        autorun: 1
        action:
          - revoke_certificate > CERTS_QUEUED_FOR_REVOCATION

    CERTS_QUEUED_FOR_REVOCATION:
        autorun: 1
        action:
          - global_noop > SUCCESS ? all_certs_revoked
          - global_noop2 > CERT_TO_REVOKE ? !all_certs_revoked

    CERT_TO_REVOKE:
        autorun: 1
        action:
           - next_cert_to_revoke > HAVE_CERT_TO_REVOKE

    PREREQS_AVAILABLE:
        autorun: 1
        action:
          - queue_certs_to_revoke > CERTS_QUEUED_FOR_REVOCATION

action:
    revoke_certificate:
        class: OpenXPKI::Server::Workflow::Activity::Tools::RevokeCertificate
        param:
            reason_code: cessationOfOperation
            comment: Revoked by SOAP Request
            flag_auto_approval : 1
            flag_batch_mode: 1

    initialize:
        class: Workflow::Action::Null
        input:
          - crr_info
          - server
          - interface
          - signer_cert
          - token_id

    check_authorized_signer:
        class: OpenXPKI::Server::Workflow::Activity::Tools::EvaluateSignerTrust
        param:
            _map_rules: soap.[% context.server %].authorized_signer

    check_prereqs_via_api:
        class: OpenXPKI::Server::Workflow::Activity::SmartCard::CheckPrereqs

    next_cert_to_revoke:
        class: OpenXPKI::Server::Workflow::Activity::Tools::WFArray
        param:
            array_name: tmp_queue
            context_key: cert_identifier
            function: shift

    queue_certs_to_revoke:
        class: OpenXPKI::Server::Workflow::Activity::Tools::WFArray
        param:
            array_name: tmp_queue
            context_key: certs_to_revoke
            function: pusharray

condition:
    all_certs_revoked:
        class: OpenXPKI::Server::Workflow::Condition::WFArray
        param:
          array_name: tmp_queue
          condition: is_empty
    
    is_requestor_authorized:
        class: Workflow::Condition::Evaluate
        param:
            test: ($context->{signer_trusted} and $context->{signer_authorized})
 

field:

    crr_info:
        label: I18N_OPENXPKI_UI_WORKFLOW_FIELD_CRR_INFO_LABEL
        name: crr_info
        type: server
        required: 0
 
    server:
        label: I18N_OPENXPKI_UI_WORKFLOW_FIELD_SERVER_LABEL
        name: server
        description: I18N_OPENXPKI_UI_WORKFLOW_FIELD_SERVER_DESC
        type: server
        required: 0

    signer_cert:
        label: I18N_OPENXPKI_UI_WORKFLOW_FIELD_SIGNER_CERT_LABEL
        name: signer_cert
        description: I18N_OPENXPKI_UI_WORKFLOW_FIELD_SIGNER_CERT_DESC
        required: 0
        type: server

    token_id: 
        name: token_id
        type: text
        required: 1



acl:
    System:
        creator: any
 

