rt: 
    backend:
        class: OpenXPKI::Server::Notification::RT
        server: http://rt.mycompany.com/
        username: admin
        password: admin
        timeout: 300

    template:
        dir:   /home/pkiadm/ca-one/rt/
       
    message:        
        csr_created:  # The message Id as referenced in the activity
            main:  # The internal handle for this ticket
                - action: open
                  queue: PKI
                  owner: pki-team
                  subject: New CSR for [% cert_subject %]
                  template: csr_created
                  to: "[% cert_info.requestor_email %]"
                  priority: 1
                  
                - action: comment
                  template: csr_created_comment
                  status: open

        csr_approved:
            main:
                - action: update
                  status: working
                  
                - action: comment
                  template: csr_approvers

        csr_rejected:
            main:
                - action: correspond
                  template: csr_rejected
                  priority: 10              

        cert_issued:
            main:
                - action: comment
                  template: cert_issued_internal
                                
                - action: correspond
                  template: cert_issued
                  status: resolved

servicenow: 
    backend:
        class: OpenXPKI::Server::Notification::ServiceNow
        server: https://demo003.service-now.com/incident.do
        username: admin
        password: admin
        timeout: 300

    template:
        dir:   /home/pkiadm/ca-one/rt/
 
    message:        
        csr_created:  # The message Id as referenced in the activity
            main:  # The internal handle for this ticket
                action: open
                short_description: CSR for [% cert_subject %]
                requestor: "[% cert_info.requestor_email %]"
                template: csr_created                  
                priority: 5                
                state: 1
                category: inquiry
                assigned_to: admin
                assignment_group: pki team                  

        csr_approved:
            main:
                action: update
                state: 6                  
                template: csr_approvers

        csr_rejected:
            main:
                action: close
                template: csr_rejected
                priority: 10              
                state: 7             

        cert_issued:
            main:
                action: close
                template: cert_issued
                status: resolved
       
                        
smtp:
    backend:
        class: OpenXPKI::Server::Notification::SMTP
        host: localhost
        port: 25
        username: ~
        password: ~
        debug: 0
        # You need to install MIME::Tools for html support
        use_html: 1

    default:
        to: "[% cert_info.requestor_email %]"
        from: no-reply@mycompany.local
        reply: helpdesk@mycompany.local
        cc: helpdesk@mycompany.local
        prefix: PKI [% meta_wf_id %]
                  
    # template settings
    template:
        dir:   /home/pkiadm/ca-one/email/

    message:    
        testmail: 
            default:   # The internal handle for this thread
                template: testmail
                subject: SMTP Notification Test
                to: "[% data.rcpt %]"
                from: no-reply@mycompany.local
                reply: ''
                cc: ''
                prefix: ''
                images:
                    banner: head.png

    
        csr_created:   # The message Id as referenced in the activity
            default:   # The internal handle for this thread
                template: csr_created_user
                subject: CSR for [% cert_subject %]                
                images:
                    banner: head.png
                    footer: foot.png
            
            raop:      # Another internal handle for a second thread
                template: csr_created_raop  # Suffix .txt is always added!
                to: reg-office@mycompany.local
                cc: ''
                reply: "[% cert_info.requestor_email %]"
                subject: CSR for [% cert_subject %]
                        
        csr_rejected:
            default:
                template: csr_rejected
                subject: CSR rejected for [% cert_subject %]
            
        cert_issued:
            default:
                template: cert_issued
                subject: certificate issued for [% cert_subject %]                
                
        scpu_notify:
            default: 
                template: scpu_notify_user
                subject: Smartcard Enrollment Verification Notice

            auth1: 
                template: scpu_notify_authcontact
                to: $auth_id1
                reply: $requestor
                subject: Smartcard Enrollment Verification Request for [% requestor %]
                                
            auth2: 
                template: scpu_notify_authcontact
                to: $auth_id1                
                reply: $requestor                
                subject: Smartcard Enrollment Verification Request for [% requestor %]                
                
                            
        
