# Transition of scep section in config.xml

testscepserver1:
    # Time that must elapse after a failed request
    retry_time: 0000000001
    # Earliest time to create a renewal request
    renewal_period: 000003
    # How long can the certificate be expried to make a renewal
    grace_period: 0000000005
    # How long a workflow can be reactivated
    #workflow_expiry: 000014 - unused
    
    authorized_signer_on_behalf:
        rule1:
            # Full DN
            subject: CN=scep-signer\.openxpki\.org,O=OpenXPKI Testing,C=DE
        rule2:
            # Wildcarded DN
            subject: CN=scep-signer-[0-9]*\.openxpki\.org.*
        rule3:
            # Special cert by identifier	
            identifier: JNHN5Hnje34HcltluuzooKVqxs2                        
    
    policy:         
        allow_anon_enroll: 0
        allow_man_authen: 1
        allow_man_approv: 1        
        max_active_certs: 1
        allow_expired_signer: 0
        auto_revoke_existing_certs: 1
