# Transition of scep section in config.xml

scep-server-1:
    # Time that must elapse after a failed request
    retry_time: 0000000001
    # Earliest time to create a renewal request
    renewal_period: 000014
    # How long can the certificate be expried to make a renewal
    grace_period: 0000000005
    # How long a workflow can be reactivated
    #workflow_expiry: 000014 - unused
    
    workflow_type: I18N_OPENXPKI_WF_TYPE_ENROLLMENT

    key_size:
    - 1024    
    - 2048
    
    authorized_signer_on_behalf:
        rule1:
            # Full DN
            subject: CN=enroll[0-9]*:scepclient,.*
    
    policy:         
        allow_anon_enroll: 0
        allow_man_authen: 1
        allow_man_approv: 1        
        max_active_certs: 1
        allow_expired_signer: 0
        auto_revoke_existing_certs: 1
        approval_points: 1
        
    # Mapping of names to OpenXPKI profiles to be used with the 
    # Microsoft Certificate Template Name Ext. (1.3.6.1.4.1.311.20.2)       
    profile_map:
        pc-client: I18N_OPENXPKI_PROFILE_USER_AUTHENTICATION

    challenge:
       value: SecretChallenge

    challenge-bind:
       mode: bind
       value@: connector:scep.connectors.challenge
       args: 
       - "[% context.url_mac %]"

    eligible:
        initial:
           value: 1

        renew:
           value: 1

connectors:
    devices:
        ## This connector just checks if the given mac 
        ## exisits in the ldap
        class: Connector::Proxy::Net::LDAP::Simple
        LOCATION: ldap://localhost:389
        base: ou=devices,dc=mycompany,dc=com
        filter: (macaddress=[% ARGS.1 %])
        binddn: cn=admin,dc=mycompany,dc=com
        password: admin
        attrs: macaddress

    devices2:
        class: Connector::Proxy::YAML
        LOCATION: /home/pkiadm/ca-one/scep.yaml
        PREFIX: status

    challenge2:
        class: Connector::Proxy::YAML
        LOCATION: /home/pkiadm/ca-one/scep.yaml
        PREFIX: challenge

    challenge:
        class: Connector::Builtin::Authentication::Password
        LOCATION: /home/pkiadm/ca-one/passwd.txt

